on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: testregistredevops.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t testregistredevops.azurecr.io/TestRegistreDevOps:${{ github.sha }}
          docker push testregistredevops.azurecr.io/TestRegistreDevOps:${{ github.sha }}